version: '3'

services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./db/Dockerfile
    volumes: 
    - ./mysql:/var/lib/mysql
#    - ./initdb.d:/docker-entrypoint-initdb.d
    environment: 
    - MYSQL_ROOT_PASSWORD=root
    - TZ=Asia/Tokyo
    ports:
    - "3306:3306"

  flask:
    container_name: flask
#    build: 
#      context: ./flask
#      dockerfile: Dockerfile
    image: shomaigu/pro-flask-slack:latest
    ports: 
      - 80:80
    restart: always
    tty: true
    volumes:
    - ./requirements.txt /usr/src/app/requirements.txt
    - ./app.py /usr/src/app/app.py
    - ./templates /usr/src/app/templates
